# Generated by Django 4.2.11 on 2026-01-26 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_remove_documentoinventario_inventario__sede_or_291bc7_idx_and_more'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Proyecto / Obra', 'verbose_name_plural': 'Proyectos y Obras'},
        ),
        migrations.RenameField(
            model_name='proyectomaterial',
            old_name='cantidad_asignada',
            new_name='cantidad_entregada',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plano',
            field=models.FileField(blank=True, null=True, upload_to='planos/%Y/%m/', verbose_name='Plano (PDF)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable'),
        ),
        migrations.AddField(
            model_name='proyectomaterial',
            name='cantidad_planificada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cant. Planificada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Código de Obra'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(help_text='El Diseñador o Planificador que creó el proyecto.', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente / Diseño'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectoasignacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_extra', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectoasignacion',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_colaboracion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='proyectomaterial',
            unique_together={('proyecto', 'producto')},
        ),
    ]
