# Generated by Django 4.2.11 on 2026-01-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectomaterial',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0, help_text='Material que regresó al almacén'),
        ),
    ]
