# Generated by Django 4.2.11 on 2026-02-12 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0003_alter_proyectomaterial_cantidad_devuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observacion_rechazo',
            field=models.TextField(blank=True, default='', help_text='Feedback del técnico al observar.'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(help_text='El Diseñador.', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('DISENO', 'En Diseño'), ('REVISION_TECNICA', 'En Revisión Técnica'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado / Por Iniciar'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='DISENO', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectomaterial',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
