# Generated by Django 4.2.11 on 2026-03-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_es_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0004_proyecto_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad transferida al técnico')),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_entregado_cuadrilla', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_cuadrilla', to='proyectos.proyecto')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_recibido_cuadrilla', to=settings.AUTH_USER_MODEL)),
                ('seriales', models.ManyToManyField(blank=True, help_text='Las MACs/Series específicas entregadas', to='inventario.itemserializado')),
            ],
            options={
                'verbose_name': 'Transferencia a Cuadrilla',
                'verbose_name_plural': 'Transferencias a Cuadrilla',
                'ordering': ['-creado_en'],
            },
        ),
    ]
