# Generated by Django 4.2.11 on 2026-06-08 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_documentoitemserializado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0005_asignacioncuadrilla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncuadrilla',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Transferencia a cuadrilla', 'verbose_name_plural': 'Transferencias a cuadrilla'},
        ),
        migrations.AlterModelOptions(
            name='proyectoasignacion',
            options={'verbose_name': 'Técnico colaborador del proyecto', 'verbose_name_plural': 'Técnicos colaboradores del proyecto'},
        ),
        migrations.AlterModelOptions(
            name='proyectomaterial',
            options={'verbose_name': 'Material de proyecto', 'verbose_name_plural': 'Materiales de proyecto'},
        ),
        migrations.AddField(
            model_name='asignacioncuadrilla',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('CONSUMIDO', 'Consumido / Instalado'), ('MERMA', 'Merma'), ('PERDIDO', 'Perdido'), ('ANULADO', 'Anulado')], default='ENTREGADO', max_length=20),
        ),
        migrations.AddField(
            model_name='asignacioncuadrilla',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacioncuadrilla',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_envio_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_observacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectomaterial',
            name='observacion_diseno',
            field=models.CharField(blank=True, default='', help_text='Nota del diseñador sobre este material.', max_length=255),
        ),
        migrations.AddField(
            model_name='proyectomaterial',
            name='observacion_revision',
            field=models.CharField(blank=True, default='', help_text='Nota del responsable PEX sobre este material.', max_length=255),
        ),
        migrations.AlterField(
            model_name='asignacioncuadrilla',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Cantidad transferida al técnico.'),
        ),
        migrations.AlterField(
            model_name='asignacioncuadrilla',
            name='seriales',
            field=models.ManyToManyField(blank=True, help_text='MACs/Series específicas entregadas.', to='inventario.itemserializado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(help_text='Diseñador / planificador que creó el proyecto.', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('DISENO', 'En Diseño'), ('REVISION_TECNICA', 'En Revisión Técnica'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado / Por Iniciar'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='DISENO', max_length=25),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observacion_rechazo',
            field=models.TextField(blank=True, default='', help_text='Feedback del responsable PEX al observar el proyecto.'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='plano',
            field=models.FileField(blank=True, help_text='Plano enviado por el diseñador.', null=True, upload_to='planos/%Y/%m/', verbose_name='Plano / Diseño'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Encargado PEX que revisa, aprueba y recibe materiales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable PEX'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectoasignacion',
            unique_together={('proyecto', 'tecnico')},
        ),
    ]
