# Generated by Django 4.2.11 on 2026-01-26 00:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REQ', 'Requerimiento'), ('SAL', 'Salida'), ('ING', 'Ingreso'), ('MER', 'Merma')], max_length=3, unique=True)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REQ', 'Requerimiento'), ('SAL', 'Salida'), ('ING', 'Ingreso'), ('MER', 'Merma')], max_length=3)),
                ('numero', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('centro_costo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('REQ_BORRADOR', 'REQ - Borrador'), ('REQ_PENDIENTE', 'REQ - Pendiente'), ('REQ_ATENDIDO', 'REQ - Atendido'), ('REQ_RECHAZADO', 'REQ - Rechazado'), ('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='REQ_BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('recibido', models.BooleanField(default=False)),
                ('recibido_en', models.DateTimeField(blank=True, null=True)),
                ('tipo_requerimiento', models.CharField(choices=[('LOCAL', 'Local (técnico)'), ('PROVEEDOR', 'Proveedor'), ('ENTRE_SEDES', 'Entre sedes')], default='LOCAL', max_length=20)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_entregados', to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='inventario.documentoinventario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Costo estándar por unidad (según 'unidad').", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('es_serializado', models.BooleanField(default=False, help_text='True para equipos con serial (ONU/Router). False para consumibles.')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('CENTRAL', 'Central'), ('SECUNDARIO', 'Secundario')], default='SECUNDARIO', max_length=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('SOLICITANTE', 'Solicitante (Técnico)'), ('ALMACEN', 'Almacén'), ('ADMIN', 'Administrador'), ('JEFA', 'Jefa / Global')], default='SOLICITANTE', max_length=15)),
                ('sede_activa', models.ForeignKey(blank=True, help_text='Sede seleccionada (usuarios globales).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='inventario.sede')),
                ('sede_principal', models.ForeignKey(blank=True, help_text='Sede fija del usuario (técnico o almacén).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_principales', to='inventario.sede')),
                ('sedes_permitidas', models.ManyToManyField(blank=True, help_text='Sedes a las que puede acceder (usuarios globales).', related_name='usuarios_globales', to='inventario.sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['sede__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('actualizado_en_operacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='ProductoSedeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='info_por_sede', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_info', to='inventario.sede')),
                ('ubicacion_referencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_referenciales', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Info Producto por Sede',
                'verbose_name_plural': 'Info Productos por Sede',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=3)),
                ('qty', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('nota', models.CharField(blank=True, max_length=250)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.sede')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemSerializado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('EN_ALMACEN', 'En almacén'), ('ASIGNADO', 'Asignado (salida)'), ('INSTALADO', 'Instalado'), ('MERMA', 'Merma / Baja')], default='EN_ALMACEN', max_length=15)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_serializados', to='inventario.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_serializados', to='inventario.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_merma', models.PositiveIntegerField(default=0)),
                ('cantidad_usada', models.PositiveIntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.documentoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='sede_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_destino', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='sede_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_origen', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='inventario.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['sede', 'nombre'], name='inventario__sede_id_0f0f68_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='uq_ubicacion_sede_nombre'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto', 'sede'], name='inventario__product_ed022c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('producto', 'sede'), name='uq_stock_producto_sede'),
        ),
        migrations.AddConstraint(
            model_name='productosedeinfo',
            constraint=models.UniqueConstraint(fields=('producto', 'sede'), name='uq_producto_sede_info'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_interno'], name='inventario__codigo__5d95d5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['barcode'], name='inventario__barcode_73eb14_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'sede', 'tipo'], name='inventario__product_b6adbb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['creado_en'], name='inventario__creado__35ad69_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['referencia'], name='inventario__referen_6dc6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemserializado',
            index=models.Index(fields=['serial'], name='inventario__serial_27fa02_idx'),
        ),
        migrations.AddIndex(
            model_name='itemserializado',
            index=models.Index(fields=['producto', 'estado'], name='inventario__product_0b91c4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemserializado',
            index=models.Index(fields=['ubicacion'], name='inventario__ubicaci_9754e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoitem',
            index=models.Index(fields=['documento', 'producto'], name='inventario__documen_f69f1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentoitem',
            constraint=models.UniqueConstraint(fields=('documento', 'producto'), name='uq_doc_item_producto'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['tipo', 'numero'], name='inventario__tipo_ff6541_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['fecha'], name='inventario__fecha_49679b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['tipo', 'estado'], name='inventario__tipo_1a1ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['sede'], name='inventario__sede_id_740d34_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['sede_origen'], name='inventario__sede_or_291bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['sede_destino'], name='inventario__sede_de_6686e6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoinventario',
            index=models.Index(fields=['recibido'], name='inventario__recibid_d29c3c_idx'),
        ),
    ]
