# Generated by Django 4.2.11 on 2026-01-22 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', 'liquidacion_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liquidacionsemanal',
            new_name='inventario__fecha_l_1b5ee2_idx',
            old_name='inventario_li_fecha_liquid_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionsemanal',
            new_name='inventario__semana_67990b_idx',
            old_name='inventario_li_semana_anio_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionsemanal',
            new_name='inventario__sede_id_a842e9_idx',
            old_name='inventario_li_sede_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidacionsemanal',
            new_name='inventario__product_2737f2_idx',
            old_name='inventario_li_producto_idx',
        ),
        migrations.AlterField(
            model_name='liquidacionsemanal',
            name='liquidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
