# Generated by Django 4.2.11 on 2026-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentoitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentoitem',
            constraint=models.UniqueConstraint(fields=('documento', 'producto'), name='uq_doc_item_producto'),
        ),
    ]
