# Generated by Django 4.2.11 on 2026-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentoinventario',
            name='inventario__sede_or_291bc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentoinventario',
            name='inventario__sede_de_6686e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentoinventario',
            name='inventario__recibid_d29c3c_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('SOLICITANTE', 'Solicitante (Técnico)'), ('ALMACEN', 'Almacén'), ('ADMIN', 'Administrador'), ('JEFA', 'Jefa / Global'), ('DISENADOR', 'Diseñador / Planificador')], default='SOLICITANTE', max_length=15),
        ),
    ]
