# Generated by Django 4.2.11 on 2026-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinventario',
            name='numero',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
