# Generated by Django 4.2.11 on 2026-01-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_documentoitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinventario',
            name='tipo_requerimiento',
            field=models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('ENTRE_SEDES', 'Entre sedes')], default='ENTRE_SEDES', max_length=20),
        ),
    ]
