# Generated by Django 4.2.11 on 2026-01-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_detalledocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinventario',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Ej: Código de Obra, Nro Factura, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='solicitante',
            field=models.ForeignKey(blank=True, help_text='Técnico o responsable de obra que solicita el material.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
