# Generated by Django 4.2.11 on 2026-01-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_documentoinventario_tipo_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoitem',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
