# Generated by Django 4.2.11 on 2026-01-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_documentoinventario_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='saldo_resultante',
            field=models.IntegerField(default=0, help_text='Stock resultante tras el movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='qty',
            field=models.IntegerField(default=0, help_text='Cantidad movida. Positiva en IN/OUT (la lógica define el signo).'),
        ),
    ]
