# Generated by Django 4.2.11 on 2026-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientoinventario_saldo_resultante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='qty',
            field=models.IntegerField(default=0, help_text='Cantidad movida. Positiva en IN/OUT.'),
        ),
        migrations.DeleteModel(
            name='DetalleDocumento',
        ),
    ]
