# Generated by Django 4.2.11 on 2026-01-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_rename_inventario_li_fecha_liquid_idx_inventario__fecha_l_1b5ee2_idx_and_more'),
        ('inventario', '0005_documentoitem_cantidad_merma_state_only'),
    ]

    operations = [
    ]
