# Generated by Django 4.2.11 on 2026-01-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_alter_movimientoinventario_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock de Técnico',
                'verbose_name_plural': 'Stocks de Técnicos',
                'unique_together': {('tecnico', 'producto')},
            },
        ),
    ]
