# Generated by Django 4.2.11 on 2026-01-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_stocktecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinventario',
            name='proveedor_manual',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Proveedor (Manual)'),
        ),
        migrations.AlterField(
            model_name='documentoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
