# Generated by Django 4.2.11 on 2026-01-23 13:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0008_remove_cantidad_entregada_state_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TECNICO', 'Liquidación técnico'), ('PROYECTO', 'Liquidación proyecto')], max_length=20)),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=20)),
                ('centro_costo', models.CharField(blank=True, default='', max_length=255)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='inventario.sede')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterField(
            model_name='documentoinventario',
            name='estado',
            field=models.CharField(choices=[('REQ_BORRADOR', 'REQ - Borrador'), ('REQ_PENDIENTE', 'REQ - Pendiente'), ('REQ_ATENDIDO', 'REQ - Atendido'), ('REQ_RECHAZADO', 'REQ - Rechazado'), ('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='REQ_BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoinventario',
            name='tipo_requerimiento',
            field=models.CharField(choices=[('LOCAL', 'Local (técnico)'), ('PROVEEDOR', 'Proveedor'), ('ENTRE_SEDES', 'Entre sedes')], default='LOCAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Costo estándar por unidad (según 'unidad').", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('SOLICITANTE', 'Solicitante (Técnico)'), ('ALMACEN', 'Almacén'), ('ADMIN', 'Administrador'), ('JEFA', 'Jefa / Global')], default='SOLICITANTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sede_activa',
            field=models.ForeignKey(blank=True, help_text='Sede seleccionada (usuarios globales).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='inventario.sede'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sede_principal',
            field=models.ForeignKey(blank=True, help_text='Sede fija del usuario (técnico o almacén).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_principales', to='inventario.sede'),
        ),
        migrations.CreateModel(
            name='ProyectoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.proyecto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_entregada', models.PositiveIntegerField(default=0)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_merma', models.PositiveIntegerField(default=0)),
                ('cantidad_usada', models.PositiveIntegerField(default=0)),
                ('cantidad_reutilizable', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.liquidacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='inventario.proyecto'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_v2', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='ProyectoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_asignada', models.PositiveIntegerField(default=0)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_merma', models.PositiveIntegerField(default=0)),
                ('cantidad_usada', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='inventario.proyecto')),
            ],
            options={
                'indexes': [models.Index(fields=['proyecto', 'producto'], name='inventario__proyect_d42c70_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyectomaterial',
            constraint=models.UniqueConstraint(fields=('proyecto', 'producto'), name='uq_proyecto_producto'),
        ),
        migrations.AddConstraint(
            model_name='proyectoasignacion',
            constraint=models.UniqueConstraint(fields=('proyecto', 'tecnico'), name='uq_proyecto_tecnico'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['sede', 'estado'], name='inventario__sede_id_93ac8f_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_1cfcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacionitem',
            index=models.Index(fields=['liquidacion', 'producto'], name='inventario__liquida_ccb42b_idx'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionitem',
            constraint=models.UniqueConstraint(fields=('liquidacion', 'producto'), name='uq_liquidacion_producto'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['sede', 'tipo', 'estado'], name='inventario__sede_id_d3adf5_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['tipo', 'tecnico'], name='inventario__tipo_0846f0_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['tipo', 'proyecto'], name='inventario__tipo_6859b5_idx'),
        ),
    ]
