# Generated by Django 4.2.11 on 2026-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_documentoinventario_proveedor_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemserializado',
            name='codigo_trazabilidad',
            field=models.CharField(blank=True, help_text="Ej: El número '44' pintado en la caja.", max_length=30, null=True, verbose_name='Cód. Pintado / Trazabilidad'),
        ),
        migrations.AddField(
            model_name='itemserializado',
            name='mac_address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='itemserializado',
            name='serial_secundario',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='D-SN / Serie Secundario'),
        ),
        migrations.AlterField(
            model_name='itemserializado',
            name='serial',
            field=models.CharField(max_length=64, unique=True, verbose_name='Serial Principal / GPON SN'),
        ),
        migrations.AddIndex(
            model_name='itemserializado',
            index=models.Index(fields=['codigo_trazabilidad'], name='inventario__codigo__3fecd8_idx'),
        ),
        migrations.AddIndex(
            model_name='itemserializado',
            index=models.Index(fields=['mac_address'], name='inventario__mac_add_89d4d9_idx'),
        ),
    ]
