# Generated by Django 4.2.11 on 2026-02-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_itemserializado_codigo_trazabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemserializado',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_serializados', to='inventario.ubicacion'),
        ),
    ]
