# Generated by Django 4.2.11 on 2026-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_itemserializado_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_activo',
            field=models.BooleanField(default=False, help_text='Si es True, el técnico NO lo consume, se queda en su poder (Ej: Herramientas).'),
        ),
    ]
