# Generated by Django 4.2.11 on 2026-05-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0011_producto_es_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCargaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=120, unique=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('finalizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_carga_inicial', to=settings.AUTH_USER_MODEL)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre_carga_inicial', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Cierre de carga inicial',
                'verbose_name_plural': 'Cierres de carga inicial',
                'ordering': ['-finalizado_en'],
            },
        ),
    ]
