# Generated by Django 4.2.11 on 2026-05-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_cierrecargainicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoItemSerializado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriales_seleccionados', to='inventario.documentoitem')),
                ('item_serializado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_seleccionados', to='inventario.itemserializado')),
            ],
            options={
                'verbose_name': 'Serial seleccionado en documento',
                'verbose_name_plural': 'Seriales seleccionados en documentos',
            },
        ),
        migrations.AddConstraint(
            model_name='documentoitemserializado',
            constraint=models.UniqueConstraint(fields=('documento_item', 'item_serializado'), name='uq_documento_item_serializado'),
        ),
    ]
