# Generated by Django 4.2.11 on 2026-08-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_documentoitemserializado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktecnico',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stocktecnico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stocktecnico',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede/almacén que entregó este material al técnico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_tecnicos', to='inventario.sede'),
        ),
        migrations.AddConstraint(
            model_name='stocktecnico',
            constraint=models.UniqueConstraint(fields=('tecnico', 'producto', 'sede'), name='uq_stock_tecnico_producto_sede'),
        ),
    ]
