# Generated by Django 4.2.11 on 2026-08-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0014_alter_stocktecnico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoinventario',
            name='retirado_por',
            field=models.ForeignKey(blank=True, help_text='Técnico o personal que retiró físicamente el material del almacén.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_retirados_por', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
    ]
