# Generated by Django 4.2.11 on 2026-09-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0016_itemserializado_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionSicv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('origen', models.CharField(choices=[('API', 'API de SICV'), ('ARCHIVO', 'Archivo importado')], default='API', max_length=10)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='EN_CURSO', max_length=12)),
                ('filas_recibidas', models.PositiveIntegerField(default=0)),
                ('filas_nuevas', models.PositiveIntegerField(default=0)),
                ('filas_repetidas', models.PositiveIntegerField(default=0)),
                ('detalle_error', models.TextField(blank=True, default='')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('ejecutada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_sicv', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(help_text='SICV exporta por sede; el reporte no la trae en cada fila.', on_delete=django.db.models.deletion.PROTECT, related_name='sincronizaciones_sicv', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Sincronización SICV',
                'verbose_name_plural': 'Sincronizaciones SICV',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMaterialSicv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_origen', models.CharField(blank=True, default='', help_text='Identificador de la fila en SICV, si lo provee.', max_length=64)),
                ('orden', models.CharField(db_index=True, max_length=32)),
                ('tipo_orden', models.CharField(blank=True, default='', max_length=80)),
                ('emision', models.DateTimeField(blank=True, null=True)),
                ('codigo_abonado', models.CharField(blank=True, default='', max_length=40)),
                ('abonado', models.CharField(blank=True, default='', max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('material', models.CharField(help_text='Nombre del material como lo escribe SICV.', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accion', models.CharField(blank=True, default='', help_text='Qué se hizo con el material: Utilizado, Retirado, etc.', max_length=40)),
                ('mac', models.CharField(blank=True, default='', max_length=40)),
                ('atencion', models.DateTimeField(blank=True, null=True)),
                ('situacion', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('tecnico', models.CharField(blank=True, default='', max_length=200)),
                ('huella', models.CharField(editable=False, max_length=64, unique=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_sicv', to='inventario.sede')),
                ('sincronizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.sincronizacionsicv')),
            ],
            options={
                'verbose_name': 'Material declarado en SICV',
                'verbose_name_plural': 'Materiales declarados en SICV',
                'ordering': ['-atencion', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='sincronizacionsicv',
            index=models.Index(fields=['sede', '-iniciada_en'], name='reportes_si_sede_id_6ef773_idx'),
        ),
        migrations.AddIndex(
            model_name='sincronizacionsicv',
            index=models.Index(fields=['estado'], name='reportes_si_estado_26e043_idx'),
        ),
        migrations.AddIndex(
            model_name='detallematerialsicv',
            index=models.Index(fields=['sede', 'atencion'], name='reportes_de_sede_id_006010_idx'),
        ),
        migrations.AddIndex(
            model_name='detallematerialsicv',
            index=models.Index(fields=['material'], name='reportes_de_materia_f8084c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallematerialsicv',
            index=models.Index(fields=['tecnico'], name='reportes_de_tecnico_1cf353_idx'),
        ),
    ]
