"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-only-change-me")

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "y")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # ✅ APPS DEL PROYECTO (Nueva Estructura)
    "inventario.apps.InventarioConfig",  # Core / Inventario Físico
    "operaciones",                       # Técnicos y Liquidaciones
    "proyectos",                         # Proyectos de Expansión
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Templates globales (si los usas)
        "APP_DIRS": True,                  # Busca templates dentro de cada app (core/templates, operaciones/templates...)
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database (Neon / PostgreSQL)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:49878",  # Browser preview proxy
    "http://localhost:49878",
]

# Para desarrollo, permitir todos los orígenes de localhost
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        f"http://127.0.0.1:{port}" for port in range(8000, 8010)
    ])
    CSRF_TRUSTED_ORIGINS.extend([
        f"http://localhost:{port}" for port in range(8000, 8010)
    ])
    # Permitir el proxy del browser preview
    CSRF_TRUSTED_ORIGINS.extend([
        f"http://127.0.0.1:{port}" for port in range(49870, 49880)
    ])
    CSRF_TRUSTED_ORIGINS.extend([
        f"http://localhost:{port}" for port in range(49870, 49880)
    ])

# CSRF Failure View
# ⚠️ IMPORTANTE: Asegúrate de mover views_csrf.py a inventario/views/csrf.py
CSRF_FAILURE_VIEW = 'inventario.views.csrf.csrf_failure'

# Para desarrollo, desactivar verificación estricta de cookies (ajusta en producción)
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_HTTPONLY = False

# Internationalization
LANGUAGE_CODE = "es-pe"
TIME_ZONE = "America/Lima"
USE_I18N = True
USE_TZ = True

# Auth redirects
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Carpeta global de estáticos (opcional)
global_static = BASE_DIR / "static"
STATICFILES_DIRS = [global_static] if global_static.exists() else []

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"