# Generated by Django 4.2.11 on 2026-01-26 00:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('LIQUIDACION_SEDE', 'Liquidación de Sede'), ('LIQUIDACION_CENTRAL', 'Liquidación Central'), ('CORRECCION', 'Corrección Manual'), ('VERIFICACION', 'Verificación')], max_length=30)),
                ('semana', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('productos_procesados', models.IntegerField(default=0)),
                ('discrepancias_detectadas', models.IntegerField(default=0)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.sede')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Liquidación',
                'verbose_name_plural': 'Logs de Liquidación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_liquidacion', models.DateField()),
                ('semana', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('stock_inicial', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_final', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_entregada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_usada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_devuelta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_merma', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('diferencia', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LIQUIDADO', 'Liquidado'), ('CONSISTENTE', 'Consistente'), ('INCONSISTENTE', 'Inconsistente'), ('REVISAR', 'Requerir Revisión')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_semanales', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_semanales', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Liquidación Semanal',
                'verbose_name_plural': 'Liquidaciones Semanales',
                'ordering': ['-fecha_liquidacion', 'sede__nombre', 'producto__nombre'],
                'indexes': [models.Index(fields=['fecha_liquidacion'], name='operaciones_fecha_l_a7bcbe_idx'), models.Index(fields=['semana', 'anio'], name='operaciones_semana_a35304_idx'), models.Index(fields=['sede'], name='operaciones_sede_id_6ac090_idx')],
                'unique_together': {('semana', 'anio', 'sede', 'producto')},
            },
        ),
    ]
